# Generated by Django 6.0.5 on 2026-05-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=20)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('title_short', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('xml_file', models.FileField(upload_to='tei_volumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('date_from', models.CharField(blank=True, max_length=20)),
                ('date_to', models.CharField(blank=True, max_length=20)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('title_desc', models.CharField(blank=True, max_length=200)),
                ('title_short', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=20)),
                ('plain_text', models.TextField()),
                ('raw_xml', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='corpora.volume')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_position', models.IntegerField(db_index=True)),
                ('text', models.CharField(max_length=20)),
                ('lemma', models.CharField(blank=True, db_index=True, max_length=20)),
                ('pos', models.CharField(blank=True, max_length=20)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpora.work')),
            ],
        ),
    ]
