# Generated by Django 6.0.5 on 2026-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0002_alter_work_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date_from',
        ),
        migrations.AlterField(
            model_name='token',
            name='text',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='volume',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='volume',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='volume',
            name='title_short',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='plain_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='raw_xml',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='title_short',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
