# Generated by Django 6.0.5 on 2026-05-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0003_remove_work_date_from_alter_token_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='date_to',
            new_name='date',
        ),
    ]
