# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0004_rename_date_to_work_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentFragmentLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("segment_index", models.IntegerField()),
                ("word_start", models.IntegerField()),
                ("word_end", models.IntegerField()),
                ("text", models.TextField()),
                ("label", models.CharField(choices=[("-1", "Негативная"), ("0", "Нейтральная"), ("1", "Позитивная")], max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sentiment_labels", to="corpora.work")),
            ],
            options={
                "ordering": ["work", "segment_index"],
                "unique_together": {("work", "segment_index")},
            },
        ),
    ]
