# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0005_sentimentfragmentlabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAnalysisRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_kind", models.CharField(choices=[("rubert", "RuBERT")], default="rubert", max_length=20)),
                ("model_name", models.CharField(max_length=200)),
                ("segment_size", models.IntegerField(default=50)),
                ("works_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SentimentAnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("segment_index", models.IntegerField()),
                ("word_start", models.IntegerField()),
                ("word_end", models.IntegerField()),
                ("text", models.TextField()),
                ("label", models.CharField(choices=[("-1", "Негативная"), ("0", "Нейтральная"), ("1", "Позитивная")], max_length=20)),
                ("confidence", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="corpora.sentimentanalysisrun")),
                ("work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sentiment_results", to="corpora.work")),
            ],
            options={
                "ordering": ["run", "work", "segment_index"],
                "unique_together": {("run", "work", "segment_index")},
            },
        ),
    ]
